project: 
  type: website
  execute-dir: project

website: 
  draft-mode: visible

page-layout: full

title-block-banner: true
lang: ko
language: 
  title-block-published: "날짜"
  title-block-modified: "개정"
date-format: "YY년 M월 D일"

toc: true

freeze: auto