---
title: 대한민국 행정구역
date: 2026-05-10
---

대한민국 행정구역

## 행정구역(광역지방자치단체)

- 특별시: 서울
- 광역시: 부산, 대구, 인천, 광주, 대전, 울산
- 특별자치시: 세종
- 도: 경기, 충북, 충남, 전남, 경북, 경남
- 특별자치도: 강원, 전북, 제주

::: {.callout-note}

### 광역행정구역의 변화

1963년 부산직할시\
1981년 인천직할시, 대구직할시\
1986년 광주직할시\
1989년 대전직할시\

1995년 인천광역시, 대전광역시, 광주광역시, 대구광역시, 부산광역시\
1997년 울산광역시\
2006년 제주특별자치도\
2012년 세종특별자치시\
2023년 강원특별자치도\
2024년 전북특별자치도

:::


## 행정구역 체계

### 특별시

- 자치구 아래 동

### 광역시

- 자치구 아래 동
- 군 아래 읍, 면

### 특별자치시

- 동, 읍, 면

### 특별자치도

- 행정 시 아래 동, 읍, 면

### 도

- 행정 시 아래 일반구 및 동, 읍, 면
- 행정 시 아래 읍, 면


## 행정구역 개편 연혁

### 서울특별시

#### 95.3.1 행정구역 개편

- 성동구를 성동구, 광진구로 분구
- 도봉구를 도봉구, 강북구로 분구
- 구로구를 구로구, 금천구로 분구


### 부산광역시
 
#### 95.3.1 행정구역 개편

- 동래구를 동래구, 연제구로 분구
- 남구를 남구, 수영구로 분구
- 북구를 북구, 사상구로 분구
- 양산군(기장읍,장안읍,일광면,정관면,철마면)이 광역시 기장군으로 편입

### 대구광역시

#### 95.3.1.

- 달성군이 광역시로 편입

#### 23.7.1

- 군위군 신설


### 인천광역시

#### 95.3.1 행정구역 개편

- 남구를 남구, 연수구로 분구
- 경기도 김포군 검단면을 서구에 편입
- 북구를 부평구, 계양구로 분구 신설
- 경기도 강화군을 광역시에 편입
- 경기도 옹진군을 광역시에 편입

#### 18.7.1

- 인천시 남구(28170)에서 인천시 미추홀구(28177)로 명칭변경


### 광주광역시

#### 95.3.1 행정구역 개편

- 서구를 서구, 남구로 분구

#### 95.4.20 행정구역 개편

- 광산구(서창출장소-서구,대촌출장소-남구)에 분구


### 울산광역시

#### 97.7.15

- 북구: 울주구(농소읍, 강동면 제외)가 울주군으로 명칭 변경
- 울주군: 울주구(농소읍, 강동면 제외)가 울주군으로 명칭 변경


### 세종특별자치시

- 2012.7.1 연기군, 공주시 일부, 충북 청원군 일부를 통합하여 신설


### 경기도

- 만안구, 동안구: '91년 이전에는 출장소였음

#### 2024.1.1

- 원미구, 소사구, 오정구 신설

#### 95.5.10

- 송탄시,평택시,평택군을 폐지하고 도농복합형태의 평택시 설치

#### 95.1.1

- 미금시와 남양주군이 도농복합형태의 남양주시 설치

#### 96.3.1

- 용인군을 용인시로 승격
- 이천군을 이천시로 승격

#### 98.4.1

- 안성군을 안성시로 승격
- 김포군을 김포시로 승격

#### 2001.3.21

- 화성군을 화성시로 승격
- 광주군을 광주시로 승격

#### 2026.2.1

- 만세구, 효행구, 병점구, 동탄구 신설

#### 2013. 9.23

- 여주군을 여주시로 승격

#### 95.3.1

- 강화군, 옹진군을 인천광역시에 편입


### 충청북도

#### '93, '94

- 동부출장소, 서부출장소

#### 95.1.1

- 청주시 상당구, 흥덕구 신설 
(상당구: 93. 94. 동부출장소 /  흥덕구 : 93. 94. 서부출장소) 
- 충주시, 중원군을 폐지하고 도농복합형태의 충주시 설치
- 제천시, 제천군을 폐지하고 도농복합형태의 제천시 설치


### 충청남도

#### 95.1.1.

- 공주시, 공주군을 폐지하고 도농복합형태의 공주시 설치
- 대천시, 보령군을 폐지하고 도농복합형태의 보령시 설치
- 온양시, 아산군을 폐지하고 도농복합형태의 아산시 설치
- 서산군, 서산시를 폐지하고 도농복합형태의 서산시 설치

#### 95. 5. 10

- 천안시, 천안군을 폐지하고 도농복합형태의 천안시 설치

#### 96.3.1.

- 논산군이 논산시로 승격

#### 2012.1.1.

- 당진군에서 당진시로 승격

### 전라남도

#### 95.1.1.

- 순천시, 승주군을 통합하여 도농복합형태의 순천시 설치
- 나주시, 나주군을 통합하여 도농복합형태의 나주시 설치
- 동광양시, 광양군을 통합하여 도농복합형태의 광양시 설치
- 광양군: '95행정구역개편으로 동광양시와 통합하여 광양시로 됨

#### 98.4.1.

- 여천군, 여천시를 통합하여 여수시로 설치


### 경상북도

#### 95.1.1.

- 포항시, 영일군 통합하여 도농복합형태의 포항시 설치
- 경주시, 경주군을 통합 도농복합형태의 경주시 설치
- 김천시, 금릉군을 통합하여 도농복합형태의 김천시 설치 
- 안동시, 안동군을 통합하여 도농복합형태의 안동시 설치
- 구미시, 선산군을 통합하여 도농복합형태의 구미시 설치
- 영주시, 영풍군을 통합하여 도농복합형태의 영주시 설치
- 영천시, 영천군을 통합하여 도농복합형태의 영천시 설치
- 상주시, 상주군을 통합하여 도농복합형태의 상주시 설치 
- 점촌시, 문경군을 통합하여 도농복합형태의 문경시 설치
- 경산시, 경산군을 통합하여 도농복합형태의 경산시 설치
- 달성군: 95년 행정구역 개편으로 대구광역시에 편입

#### 2023. 7.1.

- 군위군 폐지


### 경상남도

#### 95.1.1.

- 창원시, 창원군(동면,북면,대산면)통합 도농복합형태의 창원시 설치(2010.7.1 창원시, 마산시, 진해시를 창원시로 통합)
- 울산군이 울산시 울주구에 편입(97.7.15 울산광역시로 승격)
- 마산시, 창원군이 통합 도농복합형태의 마산시 설치(2010.7.1 창원시, 마산시, 진해시를 창원시로 통합)
- 창원군(구산면,진동면,진북면,진전면)이 마신시 합포구에 편입
- 창원군(내서면)이 마산시 회원구에 편입
- 진주시, 진양군이 통합하여 도농복합형태의 진주시 설치
- 충무시, 통영군을 통합하여 도농복합형태의 통영시 설치
- 밀양시, 밀양군을 통합하여 도농복합형태의 밀양시 설치
- 장승포시, 거제군을 통합하여 도농복합형태의 거제시 설치

#### 95.5.10.

- 삼천포시, 사천군을 통합하여 도농복합형태의 사천시 설치
- 김해시, 김해군을 통합하여 도농복합형태의 김해시 설치

#### 96.3.1.

- 양산군: 양산시로 승격

#### 97.7.15

- 울산시가 울산광역시로 승격

#### 2010.7.1.

- 창원시, 마산시, 진해시를 창원시로 통합


### 제주특별자치도

#### 2006.7.1.

- 제주도에서 제주특별자치도로 명칭변경
