---
title: Quarto Glob
---

#### Glob 사용

Quarto는 다음의 경우 파일을 특정하기 위하여 Glob을 사용한다.

- 프로젝트(project)에서 렌더링 대상(targets) 지정
- 웹사이트(website)의 자원(resources) 지정
- 리스팅(listing)에 포함할 문서(documents) 지정
- 사이드바(측면 메뉴, sidebar) 네비게이션을 자동으로 생성할 때

#### Glob 문법


::: {.callout-tip}

Glob 문법을 사용해 패턴을 일치할 때 기본값은 파일시스템의 하부 폴더까지 재귀적으로 적용한다.\
그렇게 하지 않기를 원하면 앞에 역슬래시(backslash) `/`를 사용해야 한다. (예, `*.qmd` 대신 `/*.qmd`) 

:::

- `*`   모든 것과 일치
- `{foo,bar}`   foo 또는 bar와 일치
- `[abcd]`  a, b, c 또는 d와 일치
- `[a-d]`   위와 같음
- `[!abcd]` a, b, c 또는 d를 제외한 모든 단일 문자와 일치
- `[[:<class>:]]` `<class>`[^1]에 속하는 모든 문자와 일치
    - `[[:alnum:]]` 숫자와 문자 클라스와 일치
    - `[[:digit:]abc]` - 숫자 클라스와 a, b 또는 c와 일치
- `\`, `    다음 문자 Escape(윈도우가 아닌 다른 운영체계, backtick: 윈도우 운영체계)
- `/`, `\`  경로 구분자(윈도우가 아닌 다른 운영체계, slash: 윈도우 운영체계)
- `?(foo|bar)` 없거나 한 번 {foo,bar}와 일치
- `@(foo|bar)` 한 번 {foo,bar}와 일치
- `*(foo|bar)` 여러 번(임의의 횟수) {foo,bar}와 일치
- `+(foo|bar)` 한 번 이상 {foo,bar}와 일치
- `!(foo|bar)` {foo,bar}가 아닌 모든 것과 일치
- `**` - 여러 번(임의의 횟수) 모든 경로와 일치

[^1]: POSIX 문자 클라스(Character Classes)

    | Property	| Pattern | Property | Pattern | 
    |-----------|---------|----------|---------|
    | `alnum`	| [a-zA-Z0-9] | `alpha`	| [a-zA-Z] |
    | `ascii`	| [\\x00-\\x7F] | `blank`	| [ \\t] |
    | `cntrl`	| [\\x00-\\x1F\\x7F] | `digit`	| [0-9] |
    | `graph`	| [\\x21-\\x7E] |  `lower`	| [a-z] |
    | `print`	| [\\x20-\\x7E] | `space`	| [ \\t\\r\\n\\v\\f] | 
    | `upper`	| [A-Z] | `word`	| [a-zA-Z0-9_] |
    | `xdigit` | [A-Fa-f0-9] | `punct`	| [!"\#$%&'()*+,\-./:;<=>?@\[\]^_{}~`]|
