---
title: Variables(변수)
author: [quarto.org, wintree]
date: 2026-04-21
date-modified: 2026-04-22
categories: [quarto, variable, shortcode, credentials, authorization]
lang: ko
title-block-banner: true
language: 
  title-block-modified: "개정"
---

Quarto로 렌더링할 때 동적 변수를 포함시키는 방법

#### 개요

숏코드(shortcode) 문법을 사용하여 동적으로(렌더링할 때) 포함되는 내용을 지정할 수 있다. 

#### 주요 숏코드

##### var

`var` 숏코드를 사용해 문서에 포함시킬 수 있다. 프로젝트 수준 설정 파일 `_variables.yml`을 프로젝트 파일 `_quarto.yml`과 같은 폴더에 생성하고 필요한 변수들을 정의한 후 문서에서 `{{{<var variable>}}}` 형태로 사용한다.

##### meta

`meta` 숏코드를 사용해 `{{{< meta variable >}}}` 형태로 문서의 맨 앞에 정의된 `YAML`이나 프로젝트 설정 파일 `_quarto.yml`에 지정된 `Pandoc` 메타데이터의 내용을 넣을 수 있다.

- 하위 키는 `.` 구분자(delimiter)로 표시
- 배열의 인덱스도 `.` 구분자(delimiter)로 표시
- 내용 자체가 `.`을 포함한 경우 `\\`로 제외(Escape) 처리

##### env

문서의 내용에 `meta` 숏코드를 사용해 `{{{< env ENV_VAR >}}}` 형태로 환경변수를 포항할 수 있다.


#### 숏코드 처리 제외(Escaping)

다음 두 가지 방법으로 숏코드가 처리되지 않도록 제외할 수 있다.

- 추가 `{}` 사용
- `shortcodes=false` 속성을 코드블록에 추가


#### 사전 정의된 숏코드(Built-in Shortcodes)

| Shortcode | Description |
|-----------|-------------|
| version | Quarto CLI 버전 출력 |
| var | `_variables.yml` 파일에 정의된 값(변수, variable) 출력 |
| meta | 문서 메타데이터(document metadata)에 정의된 값 출력 |
| env | 시스템 환경변수(system environment variable) 출력 |
| pagebreak | 페이지 나눔(page-break) 삽입 |
| kbd | 키보드 단축키(keyboard shortcuts) 설명 |
| video | 문서에 비디오(video) 삽입 |
| include | 다른 `qmd` 파일의 내용 포함 |
| embed | 쥬피터 노트북(Jupyter Notebook)에서 셀 삽입 |
| placeholder | 문서에 그림 지정자(placeholder images) 삽입 |
| lipsum | 문서에 텍스트 지정자(placeholder text) 삽입 |
| contents | 문서의 목차 재정렬 |


#### 프로젝트 환경변수(Environmental Variables)

- 프로젝트 수준 설정 파일 `_environment`을 프로젝트 파일 `_quarto.yml`과 같은 폴더에 생성하고 필요한 변수들을 정의한다.
- 프로젝트 프로필(Project Profiles)을 사용할 경우 설정 파일 이름에 프로필을 추가하여 `_environment-profile`로 생성한다.
- 특정 사용자 환경에서만 지정하는 변수는 `_environment.local`에 설정한다.


::: {.callout-note}

`_environment.local` 파일에 지정된 환경변수는 `_environment` 파일에 지정된 내용을 덮어 쓴다. 이 파일은 그 성격상 버전 관리에서 제외 되어야 하기 때문에 `.gitignore` 파일에 `/_*.local` 처럼 추가 되어야 한다.

:::

#### 로그인 정보 관리


::: {.callout-warning}

로그인 자격증명과 같이 프로젝트 렌더링을 위해 필요한 정보는 `_environment.required`와 `_environment.local`을 사용하여 관리하여야 한다.

:::

```{filename="_environment.required"}
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
```

```{filename="_environment.local"}
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI
```
