---
title: 라벨 및 색인
description: Lables and Legends
date: 2026-05-21
date-modified: 2026-05-21
categories: [label, legend]
---

참조: [Data Visualization with ggplot2::Cheat Sheet "Labels and Legends"](https://rstudio.github.io/cheatsheets/html/data-visualization.html#labels-and-legends)

```{r}
#| code-overflow: wrap
library(ggplot2)
n <- ggplot(mpg, aes(fl)) + geom_bar(aes(fill = fl))
p <- ggplot(mpg, aes(cty, hwy)) + geom_point(aes(shape = fl, size = cyl))
t <- ggplot(mpg, aes(cty, hwy)) + geom_point()
```

#### 개요

labs() 함수를 사용하여 그래프의 라벨 요소들을 설정

::: {.callout-tip}

##### 라벨 및 색인

    labs(x = "New x axis label",
        y = "New y axis label",
        title = "Add a title above the plot",
        subtitle = "Add a subtitle below title",
        caption = "Add a caption below plot",
        alt = "Add alt text to the plot",
        <aes> = "New <aes> legend title")

:::

```{r}
t
t + labs(x = "New x axis label",
         y = "New y axis label",
         title = "Add a title above the plot",
         subtitle = "Add a subtitle below title",
         caption = "Add a caption below plot",
         alt = "Add alt text to the plot")
```

#### 사용자 지정

##### annotate()

```{r}
t + annotate(geom = "text", x = 8, y = 9, label = "A")
```

##### guides()

```{r}
p + guides(x = guide_axis(n.dodge = 2))
```

```{r}
n + guides(fill = "none")
```

##### theme()

```{r}
n + theme(legend.position = "bottom")
```

##### scale_fill_discrete()

```{r}
n + scale_fill_discrete(name = "Title", labels = c("A", "B", "C", "D", "E"))
```
