---
title: 파이 그래프 pie graph
description: 파이 그래프(pie graph)로 비율 비교
date: 2026-05-16
date-modified: 2026-05-16
categories: [ggplot2, base graph, pie graph]
---

#### 패키지 Graphics

```{r}
#| collapse: true
# Define slice values and labels
slices <- c(75, 17, 3, 5)
labels <- c("인터넷신문", "주간신문", "일간신문", "잡지등")

# set Korean font for macOS
if (Sys.info()["sysname"] == "Darwin") {
  par(family = "Apple SD 산돌고딕 Neo")
}
# Create a simple pie chart
pie(slices, labels = labels, main = "언론사 매체별 구성 비율")
```

#### 패키지 ggplot2

```{r}
#| collapse: true
library(ggplot2)
# Create a data frame
df <- data.frame(
  media = c("인터넷신문", "주간신문", "일간신문", "잡지등"),
  count = c(75, 17, 3, 5)
)

# Create the pie chart using polar coordinates
gr <- ggplot(df, aes(x = "", y = count, fill = media)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0)
# clear background, grid, etc. and set Korean font for macOS
gr <- gr +
  if (Sys.info()["sysname"] == "Darwin") {
    theme_set(theme_void(base_family = "Apple SD 산돌고딕 Neo"))
  } else {
    theme_set(theme_void())
  }
gr <- gr + labs(title = "언론사 매체별 구성 비율")
print(gr)
```
